"""
Creates a sample input Excel file representing a UK CMT Funnel dataset
with 25 fantasy/sci-fi book series for testing the enrichment pipeline.
"""

import pandas as pd
from pathlib import Path


SAMPLE_DATA = [
    {
        "Series Name": "A Song of Ice and Fire",
        "First Book Name": "A Game of Thrones",
        "Author Name": "George R.R. Martin",
        "Publisher": "Bantam Books",
        "Year Published": 1996,
        "ISBN": "9780553103540",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 694,
        "Notes": "",
    },
    {
        "Series Name": "The Witcher",
        "First Book Name": "The Last Wish",
        "Author Name": "Andrzej Sapkowski",
        "Publisher": "Gollancz",
        "Year Published": 1993,
        "ISBN": "9780575077829",
        "Language": "English",
        "Format": "Paperback",
        "Pages": 288,
        "Notes": "Translated from Polish",
    },
    {
        "Series Name": "Mistborn",
        "First Book Name": "The Final Empire",
        "Author Name": "Brandon Sanderson",
        "Publisher": "Tor Books",
        "Year Published": 2006,
        "ISBN": "9780765311788",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 541,
        "Notes": "",
    },
    {
        "Series Name": "The Name of the Wind",
        "First Book Name": "The Name of the Wind",
        "Author Name": "Patrick Rothfuss",
        "Publisher": "DAW Books",
        "Year Published": 2007,
        "ISBN": "9780756404079",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 662,
        "Notes": "Kingkiller Chronicle #1",
    },
    {
        "Series Name": "The Stormlight Archive",
        "First Book Name": "The Way of Kings",
        "Author Name": "Brandon Sanderson",
        "Publisher": "Tor Books",
        "Year Published": 2010,
        "ISBN": "9780765326355",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 1007,
        "Notes": "",
    },
    {
        "Series Name": "Discworld",
        "First Book Name": "The Colour of Magic",
        "Author Name": "Terry Pratchett",
        "Publisher": "Colin Smythe",
        "Year Published": 1983,
        "ISBN": "9780861401420",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 210,
        "Notes": "",
    },
    {
        "Series Name": "The First Law",
        "First Book Name": "The Blade Itself",
        "Author Name": "Joe Abercrombie",
        "Publisher": "Gollancz",
        "Year Published": 2006,
        "ISBN": "9780575079793",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 515,
        "Notes": "",
    },
    {
        "Series Name": "Malazan Book of the Fallen",
        "First Book Name": "Gardens of the Moon",
        "Author Name": "Steven Erikson",
        "Publisher": "Tor Books",
        "Year Published": 1999,
        "ISBN": "9780765348784",
        "Language": "English",
        "Format": "Paperback",
        "Pages": 666,
        "Notes": "",
    },
    {
        "Series Name": "The Wheel of Time",
        "First Book Name": "The Eye of the World",
        "Author Name": "Robert Jordan",
        "Publisher": "Tor Books",
        "Year Published": 1990,
        "ISBN": "9780312850098",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 782,
        "Notes": "",
    },
    {
        "Series Name": "The Dresden Files",
        "First Book Name": "Storm Front",
        "Author Name": "Jim Butcher",
        "Publisher": "Roc",
        "Year Published": 2000,
        "ISBN": "9780451457813",
        "Language": "English",
        "Format": "Paperback",
        "Pages": 322,
        "Notes": "",
    },
    {
        "Series Name": "An Ember in the Ashes",
        "First Book Name": "An Ember in the Ashes",
        "Author Name": "Sabaa Tahir",
        "Publisher": "Razorbill",
        "Year Published": 2015,
        "ISBN": "9781595148049",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 446,
        "Notes": "",
    },
    {
        "Series Name": "Six of Crows",
        "First Book Name": "Six of Crows",
        "Author Name": "Leigh Bardugo",
        "Publisher": "Henry Holt",
        "Year Published": 2015,
        "ISBN": "9781627792127",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 465,
        "Notes": "",
    },
    {
        "Series Name": "The Poppy War",
        "First Book Name": "The Poppy War",
        "Author Name": "R.F. Kuang",
        "Publisher": "Harper Voyager",
        "Year Published": 2018,
        "ISBN": "9780062662590",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 544,
        "Notes": "",
    },
    {
        "Series Name": "Realm of the Elderlings",
        "First Book Name": "Assassin's Apprentice",
        "Author Name": "Robin Hobb",
        "Publisher": "Bantam Books",
        "Year Published": 1995,
        "ISBN": "9780553373397",
        "Language": "English",
        "Format": "Paperback",
        "Pages": 356,
        "Notes": "Farseer Trilogy #1",
    },
    {
        "Series Name": "The Chronicles of the One",
        "First Book Name": "Year One",
        "Author Name": "Nora Roberts",
        "Publisher": "St. Martin's Press",
        "Year Published": 2017,
        "ISBN": "9781250122995",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 389,
        "Notes": "",
    },
    {
        "Series Name": "The Broken Earth",
        "First Book Name": "The Fifth Season",
        "Author Name": "N.K. Jemisin",
        "Publisher": "Orbit",
        "Year Published": 2015,
        "ISBN": "9780316229296",
        "Language": "English",
        "Format": "Paperback",
        "Pages": 498,
        "Notes": "Hugo Award Winner",
    },
    {
        "Series Name": "The Inheritance Games",
        "First Book Name": "The Inheritance Games",
        "Author Name": "Jennifer Lynn Barnes",
        "Publisher": "Little, Brown",
        "Year Published": 2020,
        "ISBN": "9781368052405",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 384,
        "Notes": "",
    },
    {
        "Series Name": "Red Rising Saga",
        "First Book Name": "Red Rising",
        "Author Name": "Pierce Brown",
        "Publisher": "Del Rey",
        "Year Published": 2014,
        "ISBN": "9780345539786",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 382,
        "Notes": "",
    },
    {
        "Series Name": "The Expanse",
        "First Book Name": "Leviathan Wakes",
        "Author Name": "James S.A. Corey",
        "Publisher": "Orbit",
        "Year Published": 2011,
        "ISBN": "9780316129084",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 561,
        "Notes": "",
    },
    {
        "Series Name": "Dune",
        "First Book Name": "Dune",
        "Author Name": "Frank Herbert",
        "Publisher": "Chilton Books",
        "Year Published": 1965,
        "ISBN": "9780441013593",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 412,
        "Notes": "Hugo and Nebula Award Winner",
    },
    {
        "Series Name": "The Night Circus",
        "First Book Name": "The Night Circus",
        "Author Name": "Erin Morgenstern",
        "Publisher": "Doubleday",
        "Year Published": 2011,
        "ISBN": "9780385534635",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 387,
        "Notes": "Standalone",
    },
    {
        "Series Name": "Throne of Glass",
        "First Book Name": "Throne of Glass",
        "Author Name": "Sarah J. Maas",
        "Publisher": "Bloomsbury",
        "Year Published": 2012,
        "ISBN": "9781619630345",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 404,
        "Notes": "",
    },
    {
        "Series Name": "The Priory of the Orange Tree",
        "First Book Name": "The Priory of the Orange Tree",
        "Author Name": "Samantha Shannon",
        "Publisher": "Bloomsbury",
        "Year Published": 2019,
        "ISBN": "9781635570298",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 848,
        "Notes": "Standalone",
    },
    {
        "Series Name": "Shades of Magic",
        "First Book Name": "A Darker Shade of Magic",
        "Author Name": "V.E. Schwab",
        "Publisher": "Tor Books",
        "Year Published": 2015,
        "ISBN": "9780765376459",
        "Language": "English",
        "Format": "Hardcover",
        "Pages": 400,
        "Notes": "",
    },
    {
        "Series Name": "Cradle",
        "First Book Name": "Unsouled",
        "Author Name": "Will Wight",
        "Publisher": "Hidden Gnome Publishing",
        "Year Published": 2016,
        "ISBN": "9780989671767",
        "Language": "English",
        "Format": "Paperback",
        "Pages": 234,
        "Notes": "LitRPG / Cultivation",
    },
]

def create_sample_input():
    df = pd.DataFrame(SAMPLE_DATA)
    df["ISBN"] = df["ISBN"].astype(str)
    output_path = Path("/workspace/pipeline/sample_input.xlsx")
    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        df.to_excel(writer, sheet_name="Books", index=False)
    print(f"Sample input created: {output_path} ({len(df)} rows)")
    return output_path


if __name__ == "__main__":
    create_sample_input()
